# APT generic installation: This updates, upgrades and install all generic linux apt deps.
- hosts: localhost
  vars_files: "vars/main.yml"
  become: true
  become_user: "{{ lookup('env', 'USER') }}"

  roles:
    - user