---
# ------------------
#     APT
# ------------------
# This list of tasks regroups all the operations related to APT management.
# It is proceeded first on the global playbook.

# APT management
- name: Update the apt [ROOT]
  apt:
    upgrade=yes
    update_cache=yes
    force_apt_get=yes

# APT packages
- name: Install generic apt packages [ROOT]
  apt:
    pkg:
      - curl
      - git
      - wget
      - zsh
      - make
