---
# APT management
- hosts: localhost
  become: yes
  vars:
    account: 'q'

  tasks:

 # Docker
      #   - name : Docker
      #     block:
      #       - name : Uninstall old Docker versions
      #         ansible.builtin.shell: apt-get remove docker docker-engine docker.io containerd runc
      #         ignore_errors: True
      #       - name: Install docker dependencies
      #         ansible.builtin.apt:
      #           pkg:
      #           - ca-certificates
      #           - curl
      #           - gnupg
      #           - lsb-release
      #       - name: Set up Docker repository
      #         ansible.builtin.shell: |
      #           mkdir -p /etc/apt/keyrings
      #           curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg -y
      #           echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      #           $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      #       - name: Update the apt
      #         ansible.builtin.apt:
      #           update_cache=yes
      #           force_apt_get=yes
      #       - name: Installing Docker
      #         ansible.builtin.apt:
      #             pkg:
      #             - docker-ce
      #             - docker-ce-cli
      #             - containerd.io
      #             - docker-compose-plugin
      #       - name: Docker post-install
      #         ansible.builtin.shell: |
      #           groupadd docker
      #           usermod -aG docker $USER
      #           newgrp docker
      #           systemctl enable docker.service
      #           systemctl enable containerd.service