---
# ------------------
#     Docker
# ------------------
# These tasks are directly introduced from the official guide on Docker installation:
# https://docs.docker.com/engine/install/ubuntu/
# It regroups the core and post installation processes.

- name : Uninstall old Docker versions
  ansible.builtin.shell:
    apt-get remove docker docker-engine docker.io containerd runc
  ignore_errors: True

- name: Clean docker keyring
  ansible.builtin.shell:
    rm -f /etc/apt/keyrings/docker.gpg
  ignore_errors: True

- name: Add docker keyring
  ansible.builtin.shell:
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

- name: Add docker repository
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu noble stable
    state: present

- name: Install docker dependencies
  ansible.builtin.apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Update the apt
  ansible.builtin.apt:
    update_cache=yes
    force_apt_get=yes

- name: Installing Docker
  ansible.builtin.apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: add user to docker group
  ansible.builtin.user:
    name: "{{ USERNAME }}"
    groups: docker
    append: yes

- name: reset ssh connection to allow user changes to affect ansible user
  ansible.builtin.meta:
    reset_connection

- name: Enable docker deamon
  ansible.builtin.shell: |
    systemctl enable docker.service
    systemctl enable containerd.service
