---
# ------------------
#     filesystem
# ------------------
# This list of tasks regroups all the operations related to
# filesystem updates (add files, add specific user folders, etc).

- name: folder TEMP
  ansible.builtin.file:
    path: "/home/{{ USERNAME }}/{{ TEMP_DIR }}/"
    state: directory
  register: TEMP_DIR

- name: folder GitHub
  ansible.builtin.file:
    path: "/home/{{ USERNAME }}/Documents/GitHub"
    state: directory

- name: folder Logiciels
  ansible.builtin.file:
    path: "/home/{{ USERNAME }}/Documents/Logiciels"
    state: directory
  register: LOGICIEL_DIR


