---
# ------------------
#     filesystem
# ------------------
# This list of tasks regroups all the operations related to
# filesystem updates (add files, add specific user folders, etc).

- name: folder TEMP
  ansible.builtin.file:
    path: "{{ USER_TEMP_DIR }}"
    state: directory

- name: folder GitHub
  ansible.builtin.file:
    path: "{{ USER_GITHUB_DIR }}"
    state: directory
