---
# ------------------
#     Post Installation
# ------------------
# This task clear installation files

- name: Clear installation files
  ansible.builtin.file:
    path: "{{ USER_TEMP_DIR }}"
    state: absent
  become_user: root
