---
# ------------------
#     Post Installation
# ------------------
# This task clear installation files

- name: Clear installation files
  ansible.builtin.file:
    path: "{{ TEMP_DIR }}"
    state: absent