---
# ------------------
#     Post Installation
# ------------------
# This task clear installation files

- name: Clear installation files
  ansible.builtin.file:
    path: "{{ TEMP_DIR.path }}"
    state: absent

- name: clear wget-log files
  ansible.builtin.file:
    path: ./wget-log*
    state: absent