---
# ------------------
#     terminal
# ------------------
# This list of tasks regroups all the operations related to
# the terminal: terminator, zsh, oh-my-zsh and themes

# APT installations
- name: Terminal specific APT installation
  apt:
    pkg:
    - zsh
    - terminator
  become_user: root

# Terminator
- name: Terminator paths
  file:
    path: "/home/{{username}}/.config/terminator/plugins/"
    state: directory
    recurse: True

- name: Terminator-themes plugin
  shell:
    wget https://git.io/v5Zwz -O /home/{{username}}/.config/terminator/plugins/terminator-themes.py

- name: Terminator COPY configfile from repo
  copy:
    src: files/terminator_config
    dest: /home/{{username}}/.config/terminator/config


# OhMyZsh
- name: Downloading OhMyZsh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /home/{{username}}/TEMP/

- name: Deleting .oh-my-zsh present file
  file:
    path: /home/{{username}}/.oh-my-zsh
    state: absent

- name: Deleting .zshrc file if exist
  file:
    path: /home/{{username}}/.zshrc
    state: absent

- name: Copy .zshrc from the repo files to ~/.
  copy:
    src: files/.zshrc
    dest: /home/{{username}}/.zshrc
  become_user: "{{username}}"

- name: Installing fresh version
  ansible.builtin.shell: |
    sh /home/{{username}}/TEMP/install.sh --keep-zshrc

- name: Installing OhMyZsh deps
  ansible.builtin.shell: |
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git \
      ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
    git clone https://github.com/zsh-users/zsh-autosuggestions \
      ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

- name: Set OhMyZsh as default shell
  user: name="{{username}}" shell=/usr/bin/zsh

# Kubectl
- name: Get Kubectl last stable version
  uri:
    url: https://storage.googleapis.com/kubernetes-release/release/stable.txt
    method: GET
    return_content: yes
  register: kubectl_version

- name: Download Kubectl last stable version
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{kubectl_version.content}}/bin/linux/amd64/kubectl
    dest: /home/{{username}}/TEMP/

- name: Add kubectl to /usr/local/bin
  copy:
    src: /home/{{username}}/TEMP/kubectl
    dest: /usr/local/bin/
    mode: a+x
  become_user: root